modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
[[mods]]
modId = "bakadanmaku"
version = "${file.jarVersion}"
displayName = "Baka Danmaku"
authors = "TartaricAcid"
description = "A Live Danmaku Mod"